version: 0.2

env:
  shell: bash
  secrets-manager:
    IO_SERVER_URL: IO_INTEGRATION:IO_SERVER_URL
    IO_ACCESS_TOKEN: IO_INTEGRATION:IO_ACCESS_TOKEN
    WORKFLOW_ENGINE_SERVER_URL: IO_INTEGRATION:WORKFLOW_ENGINE_SERVER_URL
    POLARIS_SERVER_URL: IO_INTEGRATION:POLARIS_SERVER_URL
    POLARIS_ACCESS_TOKEN: IO_INTEGRATION:POLARIS_ACCESS_TOKEN
    BLACKDUCK_SERVER_URL: IO_INTEGRATION:BLACKDUCK_SERVER_URL
    BLACKDUCK_ACCESS_TOKEN: IO_INTEGRATION:BLACKDUCK_ACCESS_TOKEN

phases:
  pre_build:
    commands:
      - echo ================Getting IO Actions================
      - wget https://intelligent-security-scan.s3.us-east-2.amazonaws.com/io_actions.sh
  build:
    commands:
      - echo ================Build Maven Package and Docker Image================
      - export GITHUB_WORKSPACE=rahulguna10
      - export GITHUB_REPO_NAME=devsecops-test/aws-io-sample
      - export GITHUB_BRANCH_NAME=master
      - export IO_ASSET_ID=devsecops-test/aws-io-sample
      - export POLARIS_PROJECT_NAME=sig-devsecops/aws-io-sample
      - export BLACKDUCK_PROJECT_NAME=github-io-sample:1.0.0
      - chmod +x io_actions.sh
      - sed -i -e 's/\r$//' io_actions.sh
      - ./io_actions.sh --stage=IO --workflow.version=2021.01
  post_build:
    commands:
      - source io_actions.meta.env
      - echo ================Trigger Polaris Scan================
      - |
        if [ "$IS_SAST_ENABLED" = true ]; then 
            wget -q $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
            unzip -j polaris_cli-linux64.zip -d /tmp
            /tmp/polaris analyze -w
        fi
      - echo ================Trigger Blackduck Scan================
      - |
        if [ "$IS_SCA_ENABLED" = true ]; then 
           bash <(curl -s https://detect.synopsys.com/detect.sh) \
            --blackduck.url="$BLACKDUCK_SERVER_URL" \
            --blackduck.api.token="$BLACKDUCK_ACCESS_TOKEN" \
            --detect.tools="SIGNATURE_SCAN,DETECTOR" \
            --detect.force.success="false" \
            --detect.wait.for.results="false" \
            --detect.policy.check.fail.on.severities="UNSPECIFIED" \
            --logging.level.com.synopsys.integration="INFO"
        fi
      - echo ================STAGE IO WORKFLOWENGINE================
      - ./io_actions.sh --stage=WORKFLOW --workflow.version=2021.01 --is.sast.enabled=$IS_SAST_ENABLED --is.sca.enabled=$IS_SCA_ENABLED
reports:
  IO_SARIF_REPORT:
    files:
     - workflowengine-results.sarif.json
