version: 0.2

env:
  shell: bash
  secrets-manager:
    IO_SERVER_URL: IO_INTEGRATION:IO_SERVER_URL
    WORKFLOW_ENGINE_SERVER_URL: IO_INTEGRATION:WORKFLOW_ENGINE_SERVER_URL

phases:
  pre_build:
    commands:
      - echo ================Getting IO Actions================
      - wget https://intelligent-security-scan.s3.us-east-2.amazonaws.com/io_actions.sh
  build:
    commands:
      - echo ================Build Maven Package and Docker Image================
      - export GITHUB_WORKSPACE=rahulguna10
      - export GITHUB_REPO_NAME=devsecops-test/github-io-sample
      - export GITHUB_BRANCH_NAME=master
      - export IO_ASSET_ID=devsecops-test/github-io-sample
      - export POLARIS_PROJECT_NAME=sig-devsecops/github-io-sample
      - export BLACKDUCK_PROJECT_NAME=github-io-sample:1.0.0
      - ./io-actions.sh --stage=IO --workflow.version=2021.01
